# This is a basic workflow to help you get started with Actions

name: Benchmarking

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CPU_VARIANT: standard
  INTEGRATED_SRAM_SIZE: 0x8000       
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # RISC-V 32
  vexriscv:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          CORE_TYPE: vexriscv
        name: Instalation and simulation
        run: |
          chmod +x install.sh
          ./install.sh
          export PATH=$PATH:~/.local/bin:$(echo $PWD/riscv64-*/bin/):$PWD/or1k/bin:$PWD/lm32gcc/bin
          ./run.py --cpu-type=$CORE_TYPE --cpu-variant=$CPU_VARIANT --integrated-sram-size=$INTEGRATED_SRAM_SIZE --threads 1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: ./*/*.json

  picorv32:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          CORE_TYPE: picorv32
        name: Instalation and simulation
        run: |
          chmod +x install.sh
          ./install.sh
          export PATH=$PATH:~/.local/bin:$(echo $PWD/riscv64-*/bin/):$PWD/or1k/bin:$PWD/lm32gcc/bin
          ./run.py --cpu-type=$CORE_TYPE --cpu-variant=$CPU_VARIANT --integrated-sram-size=$INTEGRATED_SRAM_SIZE --threads 1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: ./*/*.json

  minerva:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          CORE_TYPE: minerva
        name: Instalation and simulation
        run: |
          chmod +x install.sh
          ./install.sh
          export PATH=$PATH:~/.local/bin:$(echo $PWD/riscv64-*/bin/):$PWD/or1k/bin:$PWD/lm32gcc/bin
          ./run.py --cpu-type=$CORE_TYPE --cpu-variant=$CPU_VARIANT --integrated-sram-size=$INTEGRATED_SRAM_SIZE --threads 1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: ./*/*.json

  cv32e40p:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          CORE_TYPE: cv32e40p
        name: Instalation and simulation
        run: |
          chmod +x install.sh
          ./install.sh
          export PATH=$PATH:~/.local/bin:$(echo $PWD/riscv64-*/bin/):$PWD/or1k/bin:$PWD/lm32gcc/bin
          ./run.py --cpu-type=$CORE_TYPE --cpu-variant=$CPU_VARIANT --integrated-sram-size=$INTEGRATED_SRAM_SIZE --threads 1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: ./*/*.json

  # OpenRISC
  mor1kx:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          CORE_TYPE: mor1kx
        name: Instalation and simulation
        run: |
          chmod +x install.sh
          ./install.sh
          export PATH=$PATH:~/.local/bin:$(echo $PWD/riscv64-*/bin/):$PWD/or1k/bin:$PWD/lm32gcc/bin
          ./run.py --cpu-type=$CORE_TYPE --cpu-variant=$CPU_VARIANT --integrated-sram-size=$INTEGRATED_SRAM_SIZE --threads 1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: ./*/*.json
  
  # OpenPOWER
  microwatt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          CORE_TYPE: microwatt
        name: Instalation and simulation
        run: |
          chmod +x install.sh
          ./install.sh
          export PATH=$PATH:~/.local/bin:$(echo $PWD/riscv64-*/bin/):$PWD/or1k/bin:$PWD/lm32gcc/bin
          ./run.py --cpu-type=$CORE_TYPE --cpu-variant=$CPU_VARIANT --integrated-sram-size=$INTEGRATED_SRAM_SIZE --threads 1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: ./*/*.json
  
  # LM32 
  lm32:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          CORE_TYPE: lm32
        name: Instalation and simulation
        run: |
          chmod +x install.sh
          ./install.sh
          export PATH=$PATH:~/.local/bin:$(echo $PWD/riscv64-*/bin/):$PWD/or1k/bin:$PWD/lm32gcc/bin
          ./run.py --cpu-type=$CORE_TYPE --cpu-variant=$CPU_VARIANT --integrated-sram-size=$INTEGRATED_SRAM_SIZE --threads 1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: ./*/*.json

  # Result aggregation
  table_maker:
    runs-on: ubuntu-18.04
    needs: [vexriscv, picorv32, minerva, cv32e40p, lm32, mor1kx, microwatt]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Result aggregation
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-setuptools python3-pip
          sudo pip3 install tabulate
          ./table_maker.py vexriscv/vexriscv picorv32/picorv32 minerva/minerva cv32e40p/cv32e40p lm32/lm32 mor1kx/mor1kx microwatt/microwatt
          sudo apt-get install python3-sphinx
          mv *.rst docs/sourc
          cd docs
          make html
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true
      - uses: actions/upload-artifact@v2
        with:
          name: aggregated-results
          path: |
             *.rst
              *.csv
              docs/build/*

